// <auto-generated />
using System;
using KingPriceTest.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(KingPriceTestDbContext))]
    partial class KingPriceTestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KingPriceTest.DAL.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 180, DateTimeKind.Local).AddTicks(5077),
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 180, DateTimeKind.Local).AddTicks(5082),
                            Name = "SuperUser"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 180, DateTimeKind.Local).AddTicks(5085),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("KingPriceTest.DAL.Models.GroupPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GroupPermission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 181, DateTimeKind.Local).AddTicks(29),
                            GroupId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 181, DateTimeKind.Local).AddTicks(33),
                            GroupId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 181, DateTimeKind.Local).AddTicks(56),
                            GroupId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 181, DateTimeKind.Local).AddTicks(59),
                            GroupId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 181, DateTimeKind.Local).AddTicks(62),
                            GroupId = 2,
                            PermissionId = 3
                        });
                });

            modelBuilder.Entity("KingPriceTest.DAL.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 180, DateTimeKind.Local).AddTicks(6374),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 180, DateTimeKind.Local).AddTicks(6378),
                            Name = "SuperUser"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 180, DateTimeKind.Local).AddTicks(6381),
                            Name = "User"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 180, DateTimeKind.Local).AddTicks(6383),
                            Name = "Restricted"
                        });
                });

            modelBuilder.Entity("KingPriceTest.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Approved = true,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 180, DateTimeKind.Local).AddTicks(3483),
                            Email = "admin@admin.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "admin"
                        });
                });

            modelBuilder.Entity("KingPriceTest.DAL.Models.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserGroup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 180, DateTimeKind.Local).AddTicks(7813),
                            GroupId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 180, DateTimeKind.Local).AddTicks(7817),
                            GroupId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 180, DateTimeKind.Local).AddTicks(7820),
                            GroupId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 180, DateTimeKind.Local).AddTicks(7822),
                            GroupId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedDateTime = new DateTime(2024, 3, 16, 11, 6, 44, 180, DateTimeKind.Local).AddTicks(7825),
                            GroupId = 3,
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
